# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Good Question
tagline:          'where all questions are good ones :)'
description:      
url:              https://mrinalinitavag.github.io
baseurl:          /

author:
  name:           'Mrinalini Tavag'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrinalinitavag/mrinalinitavag.github.io
